spring:
  application:
    name: trace-a
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9412/
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: guest
#        password: 123456
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"